version: '3.7'

services:
  
  balancer:
    image: nginx:1.17.8-alpine
    container_name: balancer
    networks:
      webnet:
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - blue
      - green
    links:
      - blue:blue
      - green:green

  blue:
    image: echo:blue
    command: node index.js
    expose:
      - 3000
    networks:
      - webnet
  green:
    image: echo:green
    command: node index.js
    expose:
      - 3000
    networks:
      - webnet

networks:
  webnet:
